name: tests

on:
  pull_request

jobs:
  build: 
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
      - run: npm install

      - name: Build and publish to docker
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: urjashee09/training-api
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
    
